import shutil
import subprocess
from pathlib import Path

from mutagen.easyid3 import EasyID3
from mutagen.flac import FLAC


def _check_tool(name):
    if shutil.which(name) is None:
        raise RuntimeError(f"Required tool '{name}' is not installed or not on PATH.")


def _write_metadata(file_path: Path, metadata: dict):
    fmt = file_path.suffix.lower()
    tags = {}
    if metadata.get("artist"):
        tags["artist"] = metadata["artist"]
    if metadata.get("album"):
        tags["album"] = metadata["album"]
    if metadata.get("year"):
        tags["date"] = metadata["year"]
    if metadata.get("genre"):
        tags["genre"] = metadata["genre"]

    if not tags:
        return

    if fmt == ".mp3":
        audio = EasyID3(file_path)
        for key, value in tags.items():
            audio[key] = value
        audio.save()
    elif fmt == ".flac":
        audio = FLAC(file_path)
        for key, value in tags.items():
            audio[key] = value
        audio.save()


def rip_cd(device: str, output_dir: Path, format: str, metadata: dict):
    _check_tool("cdparanoia")

    temp_dir = output_dir / "_tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    try:
        subprocess.run(["cdparanoia", "-B", "-d", device], check=True, cwd=temp_dir)
        wav_files = sorted(temp_dir.glob("*.wav"))

        if not wav_files:
            raise RuntimeError("No WAV files were generated by cdparanoia.")

        for wav_file in wav_files:
            target_name = wav_file.name
            output_file = output_dir / target_name

            if format == "wav":
                output_file = output_dir / wav_file.name
                wav_file.replace(output_file)
            else:
                _check_tool("ffmpeg")
                output_file = output_dir / wav_file.with_suffix(f".{format}").name
                subprocess.run([
                    "ffmpeg",
                    "-y",
                    "-i",
                    str(wav_file),
                    str(output_file),
                ], check=True)
                wav_file.unlink()

            if format in {"mp3", "flac"}:
                _write_metadata(output_file, metadata)

        if metadata.get("artist") and metadata.get("album"):
            artist_dir = output_dir / metadata["artist"].strip()
            album_dir = artist_dir / metadata["album"].strip()
            album_dir.mkdir(parents=True, exist_ok=True)
            for file in output_dir.glob(f"*.{format}"):
                file.replace(album_dir / file.name)
    finally:
        if temp_dir.exists():
            for item in temp_dir.iterdir():
                item.unlink()
            temp_dir.rmdir()
